<a href="https://colab.research.google.com/github/EduardoWS/Calculo-Numerico/blob/main/Cholesky.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def chol_decomp(A):
    # A: matriz SPD
    # H: triang. inferior, tal que A = H*H'
    n = A.shape[0]
    H = np.tril(A)
    
    for k in range(n-1):
        H[k, k] = np.sqrt(H[k, k])
        H[k+1:n, k] = H[k+1:n, k] / H[k, k]
        
        for j in range(k+1, n):
            H[j:n, j] = H[j:n, j] - H[j:n, k] * H[j, k]
    
    H[n-1, n-1] = np.sqrt(H[n-1, n-1])
    return H

In [4]:
#dados

A = np.array([[3, 2, 0],
              [2, 5, 1],
              [0, 1, 3]])

H = chol_decomp(A)
print(H)

[[1 0 0]
 [2 1 0]
 [0 1 1]]
