<a href="https://colab.research.google.com/github/EduardoWS/Calculo-Numerico/blob/main/DecompositionQR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

def classic_QR_decomposition(A):
    """Computes the classic QR decomposition of the matrix A using the Gram-Schmidt algorithm.

    Parameters:
    -----------
    A : numpy array
        The matrix to be decomposed. Must be a 2-dimensional array.

    Returns:
    --------
    Q : numpy array
        The orthogonal matrix.
    R : numpy array
        The upper triangular matrix.
    """
    # Get the number of rows and columns in the input matrix
    m, n = A.shape

    # Create a new matrix Q with the same shape as A and fill it with zeros
    Q = np.zeros((m, n))

    # Create a new matrix R with the same shape as A and fill it with zeros
    R = np.zeros((n, n))

    # Perform the Gram-Schmidt algorithm
    for j in range(n):
        # Set v to the j-th column of A
        v = A[:, j]

        # Subtract the projection of v onto the previous j-1 columns of Q
        for i in range(j):
            u = Q[:, i]
            v -= np.dot(v, u) * u

        # Set the j-th column of Q to the normalized v
        Q[:, j] = v / np.linalg.norm(v)

        # Set the j-th row of R to the projection of A onto the j-th column of Q
        for i in range(j+1):
            R[i, j] = np.dot(Q[:, i], A[:, j])

    return Q, R

In [18]:
A = np.array([[3, 1],
              [4, -1]], dtype='double')

Q, R = classic_QR_decomposition(A)

print(Q)
print(R)

[[ 0.6  0.8]
 [ 0.8 -0.6]]
[[5.  0. ]
 [0.  1.4]]


In [21]:
A = np.array([[1, 1, 0],
              [0, 1, 2],
              [1, 0, 1],
              [0, 1, 3]], dtype='double')

Q, R = classic_QR_decomposition(A)

print(Q)
print()
print(R)

[[ 0.70710678  0.31622777 -0.60246408]
 [ 0.          0.63245553  0.0860663 ]
 [ 0.70710678 -0.31622777  0.60246408]
 [ 0.          0.63245553  0.51639778]]

[[ 1.41421356e+00  1.11022302e-16 -1.11022302e-16]
 [ 0.00000000e+00  1.58113883e+00  4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  2.32379001e+00]]


In [22]:
import numpy as np

def modified_QR_decomposition(A):
    """Computes the modified QR decomposition of the matrix A using the Gram-Schmidt algorithm.

    Parameters:
    -----------
    A : numpy array
        The matrix to be decomposed. Must be a 2-dimensional array.

    Returns:
    --------
    Q : numpy array
        The orthogonal matrix.
    R : numpy array
        The upper triangular matrix.
    """
    # Get the number of rows and columns in the input matrix
    m, n = A.shape

    # Create a new matrix Q with the same shape as A and fill it with zeros
    Q = np.zeros((m, n))

    # Create a new matrix R with the same shape as A and fill it with zeros
    R = np.zeros((n, n))

    # Perform the modified Gram-Schmidt algorithm
    for j in range(n):
        # Set v to the j-th column of A
        v = A[:, j]

        # Subtract the projection of v onto the previous j-1 columns of Q
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], v)
            v -= R[i, j] * Q[:, i]

        # Set the j-th column of Q to the normalized v
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

In [24]:
A = np.array([[3, 1],
              [4, -1]], dtype='double')

Q, R = modified_QR_decomposition(A)

print(Q)
print(R)

[[ 0.6  0.8]
 [ 0.8 -0.6]]
[[ 5.  -0.2]
 [ 0.   1.4]]
