<a href="https://colab.research.google.com/github/EduardoWS/Calculo-Numerico/blob/main/EliminacaoDeGauss_Pivo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

def elimination_pivo(A, b):
    n = np.shape(A)[0]
    newA = np.copy(A)   # cria uma matriz numpy
    newb = np.copy(b)   # cria uma matriz numpy

    for k in np.arange(n-1):
        p = np.argmax(np.abs(newA[k:n,k]))  # pega o índice do maior elemento absoluto
        newA[[k,p],k:n] = newA[[p,k],k:n]   # troca de posição o maior elemento absoluto
        newb[[k,p]] = newb[[p,k]]   # troca de posição o maior elemento absoluto

        for i in np.arange(k+1,n):      # começa em k+1 e vai até n
            m = newA[i,k]/newA[k,k]     # gera o multiplicador
            newA[i,k:n] = newA[i,k:n] - m*newA[k,k:n]
            newb[i] = newb[i] - m*newb[k]

    return newA, newb

In [32]:
def solveUpperTriangular(U,y):
    n = np.shape(y)[0]
    x = np.zeros(n)

    for i in np.arange(n-1,-1,-1):
        x[i] = (y[i]-U[i,i+1:n].dot(x[i+1:n]))/U[i,i]

    return x

In [36]:
# Dados do problema
A = np.array([[1, 1, 1],  
              [1, 0,10],  
              [0,10, 1]], dtype='double')
b = [0,-48,25]

# Obtenção do sistema triangular superior equivalente
U, b = elimination_pivo(A, b)
print("U = ", U)
print("b = ", b)
x = solveUpperTriangular(U, b)
print("x = ", x)

U =  [[ 1.  1.  1.]
 [ 0. -1.  9.]
 [ 0.  0. 91.]]
b =  [   0  -48 -455]
x =  [ 2.  3. -5.]


# Testes:

In [ ]:
A = [[3,  2,  4],
     [1,  1,  2],
     [4,  3, -2]]

newA = np.copy(A)
n = np.shape(A)[0]
print(n)
for i in np.arange(10, 0, -1):
    print(i)

In [28]:
newA[1, 0:n]    # imprime linha 1
newA[0:n, 0]    # imprime coluna 0

array([3, 1, 4])