<a href="https://colab.research.google.com/github/EduardoWS/Calculo-Numerico/blob/main/Inversa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

A = np.array([[2, 1],
             [5, 3]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[ 1. -2.  5.]
 [ 0.  1. -4.]
 [ 0.  0.  1.]]


In [53]:
# Algoritmo que corresponde ao passo 2 da eliminação de Gauss
def elimination(A, b):
    n = len(b)
    x = [0]*n

    # Laço para calcular os pivôs
    for k in list(range(1, n, 1)):

        for i in list(range(k+1, n+1, 1)):
            m = (A[i-1][k-1])/(A[k-1][k-1])
            A[i-1][k-1] = 0
            b[i-1] = b[i-1] - m*b[k-1]

            for j in list(range(k+1, n+1, 1)):
                A[i-1][j-1] = A[i-1][j-1] - m*A[k-1][j-1]
    
    return A, b


# Algoritmo que corresponde ao passo 1 da eliminação de Gauss
def solveUpperTriangular(U, b):
    n = len(b)      # índice começa em 0 e vai até n-1
    x = [0]*n       # criando um vetor com n valores 0

    x[n-1] = b[n-1]/U[n-1][n-1]     # calculando x_n
    
    # Laço para encontrar os n-1 valores de x
    for i in list(range(n-1, 0, -1)):
        s = 0
        # Calculando a soma dos termos associados
        # a todas as variáveis x_n até x_i+1
        for j in list(range(i+1, n+1, 1)):
            s = s + U[i-1][j-1]*x[j-1]
        
        # Cálculo de x_i: em Python x[i-1]
        x[i-1] = (b[i-1] - s)/(U[i-1][i-1])

    return x


def sub_regressiva(U,y):
    n = np.shape(y)[0]
    x = np.zeros(n)

    for i in np.arange(n-1,-1,-1):
        x[i] = (y[i]-U[i,i+1:n].dot(x[i+1:n]))/U[i,i]

    return x


def eliminacao_gauss_pivo(A,b):
    n = np.shape(A)[0]
    newA = np.copy(A)
    newb = np.copy(b)

    for k in np.arange(n-1):
        p = np.argmax(np.abs(newA[k:n,k]))
        newA[[k,p],k:n] = newA[[p,k],k:n]
        newb[[k,p]] = newb[[p,k]]

        for i in np.arange(k+1,n):
            m = -newA[i,k]/newA[k,k]
            newA[i,k:n] = newA[i,k:n] + m*newA[k,k:n]
            newb[i] = newb[i] + m*newb[k]

    return newA,newb

In [59]:
# Dados do problema
A1 = np.array([[1, 2, 3],
              [0, 1, 4],
              [0, 0, 1]])

A2 = np.array([[2, 1],
             [5, 3]])

In [63]:
# calculando a inversa
def inversa(A):
    n = np.shape(A)[0]
    A_inv = np.zeros((n, n), dtype=int)
    e = np.eye(n)

    for i in np.arange(n):
        b = e[0:n, i]
        Aup, b = elimination(A, b)
        x = solveUpperTriangular(Aup, b)
        A_inv[0:n, i] = x[0:n]

    return A_inv



A_inv = inversa(A1)
print(A_inv)

[[ 1 -2  5]
 [ 0  1 -4]
 [ 0  0  1]]
